/**
* @file read_write.c
* @brief This file contains the functions needed to read and write images
* @details the code is a modified version of the code given by the professor in the assignment description, original code:
*   https://github.com/Foundations-of-HPC/Foundations_of_HPC_2022/blob/main/Assignment/exercise1/read_write_pgm_image.c 
**/

#include <stdlib.h>
#include <stdio.h> 
#include<mpi.h>
#include "read_write.h"

#define XWIDTH 256
#define YWIDTH 256
#define MAXVAL 65535

/**
* Writes a pbm image to a file.
* @param image a pointer to the memory region that contains the image.
* @param maxval either 255 or 65536 (in case of a 16 bit image)
* @param xsize x dimension of the image
* @param ysize y dimension of the image
* @param image_name the name of the file to be written
*/
void write_pbm(const void *image, const unsigned int maxval, const unsigned int xsize,
               const unsigned int ysize, const char *image_name) {
  FILE* image_file; 
  image_file = fopen(image_name, "w"); 
  int color_depth = 1 + ( maxval > 255 );

  // write image header
  fprintf(image_file, "P5\n# generated by\n# Davide Capone and Sandro Junior Della Rovere\n%d %d\n%d\n", xsize, ysize, maxval);
  fwrite(image, 1, xsize*ysize*color_depth, image_file);  
  fclose(image_file); 
  return ;
}

/**
* Reads a pbm image from a file.
* @param image a pointer to the pointer that rappresent the memory region which will contain the image
* @param maxval a pointer to the int that stores the maximum intensity in the image (either 255 or 65536)
* @param xsize a pointer to the x dimension of the image
* @param ysize a pointer to the y dimension of the image
* @param image_name the name of the file to be read
*/
void read_pbm(void **image, unsigned int *maxval, unsigned int *xsize, unsigned int *ysize, const char *image_name) {
    FILE* image_file; 
    char magic[2];
    char *line = NULL;
    size_t buffer, n = 0;
    *image = NULL;
    *xsize = *ysize = *maxval = 0;
    image_file = fopen(image_name, "r"); 

    // get the magic number 
    buffer = fscanf(image_file, "%2s%*c", magic);  

    // skip all comments
    buffer = getline( &line, &n, image_file);        

    while ( (buffer > 0) && (line[0]=='#') ) {
        buffer = getline( &line, &n, image_file);
    }

    // read width and height
    if (buffer > 0) {
        buffer = sscanf(line, "%d%*c%d%*c%d%*c", xsize, ysize, maxval);
        if ( buffer < 3 ) fscanf(image_file, "%d%*c", maxval);
    } else { // header read error
      *maxval = -1; 
      free( line );
      return;
    }

    free( line );
    int color_depth = 1 + ( *maxval > 255 );
    unsigned int size = *xsize * *ysize * color_depth;
  
    if ( (*image = (char*)malloc( size )) == NULL ) {
        fclose(image_file);
        *maxval = -2;         
        *xsize  = 0;
        *ysize  = 0;
        return;
    }

    if ( fread( *image, 1, size, image_file) != size ) {
        free( image );
        image   = NULL;
        *maxval = -3;         
        *xsize  = 0;
        *ysize  = 0;
    }  
    
  fclose(image_file);
  return;
} 